CREATE ROLE root
	LOGIN
	PASSWORD 'root_password';

CREATE ROLE thegan
	LOGIN
	PASSWORD 'user_password';

REVOKE ALL ON DATABASE values_db FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;

GRANT CONNECT ON DATABASE values_db TO thegan;

GRANT USAGE ON SCHEMA public TO thegan;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO thegan;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO thegan;

ALTER DEFAULT PRIVILEGES FOR ROLE root IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO thegan;

ALTER DEFAULT PRIVILEGES FOR ROLE root IN SCHEMA public
GRANT USAGE, SELECT, UPDATE
ON SEQUENCES TO thegan;

REVOKE CREATE ON SCHEMA public FROM thegan;
